package io.eleven19.kymora.vfs

import java.nio.charset.StandardCharsets

import kyo.*
import kyo.test.*

class VfsStreamWriteTests extends Test[Any]:

    "example: write a generated byte stream to an artifact file" in {
        val program =
            for
                fs <- Vfs.inMemory.init
                path = VPath.root / "target" / "classes" / "Main.class"
                bytes = Stream.init(
                    Chunk(
                        Chunk.from("CAFEBABE".getBytes(StandardCharsets.UTF_8).toSeq),
                        Chunk.from("-bytecode".getBytes(StandardCharsets.UTF_8).toSeq)
                    ),
                    chunkSize = 1
                )
                _    <- Scope.run(fs.writeBytesStream(path, bytes))
                read <- fs.read(path)
            yield assert(read == "CAFEBABE-bytecode")

        program
    }

    "example: write streamed log text and read it back" in {
        val program =
            for
                fs <- Vfs.inMemory.init
                path      = VPath.root / "logs" / "compile.log"
                fragments = Stream.init(Chunk("compile: started\n", "compile: finished\n"), chunkSize = 1)
                _    <- Scope.run(fs.writeTextStream(path, fragments))
                text <- fs.read(path)
            yield assert(text == "compile: started\ncompile: finished\n")

        program
    }

    "example: write streamed report lines with stable newline behavior" in {
        val program =
            for
                fs <- Vfs.inMemory.init
                path  = VPath.root / "reports" / "summary.txt"
                lines = Stream.init(Chunk("tests=42", "failed=0"), chunkSize = 1)
                _      <- Scope.run(fs.writeLinesStream(path, lines))
                text   <- fs.read(path)
                parsed <- fs.readLines(path)
            yield
                assert(text == "tests=42\nfailed=0\n")
                assert(parsed == Chunk("tests=42", "failed=0"))

        program
    }

    "example: append streamed output to an existing file" in {
        val program =
            for
                fs <- Vfs.inMemory.init
                path = VPath.root / "logs" / "build.log"
                _ <- fs.write(path, "build: queued\n")
                updates = Stream.init(Chunk("build: running\n", "build: done\n"), chunkSize = 1)
                _    <- Scope.run(fs.appendTextStream(path, updates))
                text <- fs.read(path)
            yield assert(text == "build: queued\nbuild: running\nbuild: done\n")

        program
    }

    "example: path-first stream writes inside Vfs.run" in {
        val program =
            for
                fs <- Vfs.inMemory.init
                path  = VPath.root / "generated" / "routes.conf"
                lines = Stream.init(Chunk("GET /health", "POST /compile"), chunkSize = 1)
                text <- Vfs.run(fs) {
                    for
                        _      <- path.writeLinesStream(lines)
                        loaded <- path.read
                    yield loaded
                }
            yield assert(text == "GET /health\nPOST /compile\n")

        program
    }

    "example: write streamed data inside a scoped temp directory" in {
        val program =
            for
                fs <- Vfs.inMemory.init
                result <- Vfs.run(fs) {
                    Scope.run {
                        for
                            dir <- Vfs.tempDir(prefix = "stream-")
                            file = dir / "analysis.txt"
                            logs = Stream.init(Chunk("scan\n", "index\n", "emit\n"), chunkSize = 1)
                            _    <- file.writeTextStream(logs)
                            text <- file.read
                        yield text
                    }
                }
            yield assert(result == "scan\nindex\nemit\n")

        program
    }

    "example: mounted VFS routes streamed writes to the mounted backend" in {
        val program =
            for
                backend <- Vfs.inMemory.init
                mounted <- Vfs.mounted.init(Mount(VPath.root / "workspace", backend))
                path   = VPath.root / "workspace" / "out" / "artifact.txt"
                chunks = Stream.init(Chunk("alpha", "-beta"), chunkSize = 1)
                _    <- Scope.run(mounted.writeTextStream(path, chunks))
                text <- backend.read(VPath.root / "out" / "artifact.txt")
            yield assert(text == "alpha-beta")

        program
    }

    "empty replace stream creates and truncates an empty file" in {
        val program =
            for
                fs <- Vfs.inMemory.init
                path = VPath.root / "empty" / "payload.bin"
                _    <- fs.write(path, "stale")
                _    <- Scope.run(fs.writeBytesStream(path, Stream.empty[Chunk[Byte]]))
                read <- fs.readBytes(path)
            yield assert(read.toArray.toSeq == Seq.empty[Byte])

        program
    }

    "explicit charset overload round-trips non-UTF-8 text" in {
        val program =
            for
                fs <- Vfs.inMemory.init
                path = VPath.root / "encodings" / "latin1.txt"
                text = Stream.init(Chunk("olá", " mundo"), chunkSize = 1)
                _    <- Scope.run(fs.writeTextStream(path, text, StandardCharsets.ISO_8859_1))
                read <- fs.read(path, StandardCharsets.ISO_8859_1)
            yield assert(read == "olá mundo")

        program
    }

    "stream failure propagates while preserving data written before the failure" in {
        val path = VPath.root / "streams" / "partial.txt"
        val stream =
            Stream[Chunk[Byte], Abort[VfsError]]:
                Emit.value(Chunk(Chunk.from("before".getBytes(StandardCharsets.UTF_8).toSeq)))
                    .andThen:
                        Abort.fail(VfsError.Unsupported(path, "source stream failed"))

        val program =
            for
                fs     <- Vfs.inMemory.init
                result <- Abort.run[VfsError](Scope.run(fs.writeBytesStream(path, stream)))
                read   <- fs.read(path)
            yield
                assert(result.failure.exists {
                    case VfsError.Unsupported(errorPath, operation) =>
                        errorPath == path && operation == "source stream failed"
                    case _ =>
                        false
                })
                assert(read == "before")

        program
    }

    "createFolders false preserves parent-missing failure behavior" in {
        val program =
            for
                fs <- Vfs.inMemory.init
                path   = VPath.root / "missing" / "payload.txt"
                stream = Stream.init(Chunk("payload"))
                result <- Abort.run[VfsError](Scope.run(fs.writeTextStream(path, stream, createFolders = false)))
            yield assert(result.failure.exists(_.isInstanceOf[VfsError.NotFound]))

        program
    }

end VfsStreamWriteTests
